### ISSUE TITLE
NO  US-EAST-2  Resion selection on the app setting

### ISSUE THREAD

**Issue by Yurikohitomi** [amzn/selling-partner-api-samples#24]
I followed the instructions to install it, but US-EAST-2 doesn't appear in the Region section of the app settings window.
no support on US-EAST-2 or was something missing in my installation process?

**Comment by leonardonakagawa** [comment]
Hi @Yurikohitomi,

You tried to (1) configure US-EAST-2 in the app.config file or (2) in the deployment script when it executes the `aws configure` command? 


For (1) The app.config files accepts only NA|EU|FE values, and it maps to global SP-API endpoints.
For (2) You can just type us-east-2 when the deployment asks you for default region name like `Default region name []: us-east-2`


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Yurikohitomi** [comment]
Hi @leonardonakagawa 

The powershell console history shows:
Default region name [None]: us-east-2
Default output format [None]:
　seems I typed in "us-east-2".

Thanks,
YH

**Comment by leonardonakagawa** [comment]
Hi @Yurikohitomi,

What is the use case you are trying to deploy?

**Comment by Yurikohitomi** [comment]
Hi @leonardonakagawa ,

listings.　I checked below.
https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/listings

Thanks,

**Comment by leonardonakagawa** [comment]
Hi @Yurikohitomi,

I talked with the backend team owner of the solution and right now it is restricted to US-EAST-1, EU-WEST-1, US-WEST-2.  I send them the feedback, and we are going to analyze the possibility of increasing the number of regions for the solution work.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Yurikohitomi** [comment]
Hi @leonardonakagawa ,

Thanks anyway.
