### ISSUE TITLE
file name inappropriate

### ISSUE THREAD

**Issue by zreiss** [amzn/selling-partner-api-samples#4]
Why is there a file called 
**pom.xml**??!!

**Describe the bug**

**Use case and programming language**
The bug is related to the following use case and programming language:
* **Use case:** [e.g. Merchant Fulfillment]
* **Programming language:** [e.g. Java]

**Relevant code section**
The root-cause of the bug is related to the following sections of the code:
* [e.g. selling-partner-api-samples/use-cases/.../MyClass.java]
* ...

**To reproduce**
2. Specify input: '...'
3. Execute '....'

**Expected behavior**

**Screenshots, logs, or other**
If applicable, add screenshots, logs or another resource to help explain your problem.

**Additional context**

**Comment by rodrifed** [comment]
Hi @zreiss,

The **pom.xml** file contains relevant information about a Maven project such as configuration details, dependencies, etc.
You can find more details in the following link: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html.

Thank you,
Federico
Selling Partner Developer Services
