### ISSUE TITLE
/use-cases/fulfillment-inbound skips over the FBA_INB_0182 part of the workflow

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-samples#52]
/use-cases/fulfillment-inbound skips over the FBA_INB_0182 part of the workflow

Seller Support claims this is not currently supported by the API.  It would be good to confirm that one way or the other, and if it's not supported by the API, to link out to the relevant documentation on what to do outside of the API.

**Comment by puppsupr** [comment]
Hi @johnkw,
Can you provide the request and response with inboundPlanID ?

**Comment by johnkw** [comment]
https://github.com/amzn/selling-partner-api-models/issues/556 has the full description of the API failure.  The plan creation step which is currently step 1 on https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound needs to be renumbered as step 2.  The real step 1 is doing something to configure SKUs to be accepted by the new API system for the Plan creation step.  (What that is exactly is what I'm not sure of.  Seller Support indicates it needs to be done outside of the API itself, because the API is not yet fully implemented.  But there's no authoritative documentation to back up what Support is claiming, and historically there have been miscommunications there, so I don't know whether to believe them or not.)

**Comment by puppsupr** [comment]
HI [johnkw](https://github.com/johnkw),
Typically you need to give the right prep and label owner for the SKUs when creating the inbound plan. To get the right label and prep owner there is no API availability right now. You need to use seller central Send to Amazon for this data. We have new APIs coming up to get this programmatically shortly. Please track [Announcements ](https://developer-docs.amazon.com/sp-api/changelog) to track the new releases.

**Comment by johnkw** [comment]
Ok, thanks, but if that's the answer it needs to be documented as step 1 on https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound because right now if you follow the instructions on that page you get blocked by the `FBA_INB_0182` issue and there's no way to proceed.
