### ISSUE TITLE
Create a sample workflow for editing a listing

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-samples#56]
Can you create a sample workflow for editing a listing using the new non-deprecated options, now that the feed file update is deprecated?

Previously, the workflow was extremely simple:

1. Go to https://sellercentral.amazon.com/listing/cards/add-product?style=standalone and type in your product type.
2. Download the template spreadsheet, fill it out, save it as a CSV.
3. Upload via `/feeds/2021-06-30/feeds`.

Now however with `/feeds/2021-06-30/feeds` being deprecated, what is step 1?  There's no "JSON" or whatever thing to download anywhere that I can find on SellerCentral.

See https://github.com/amzn/selling-partner-api-models/issues/547 on the prior bug report regarding no documented workflow on this.  Unfortunately it was marked closed without actually being addressed. Not sure why really.

**Comment by jawheral** [comment]
Hi @johnkw,

We do provide guidance on the new listings workflow. Please check the following resources:
- [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide)
- [Listings Management Workflow Migration](https://developer-docs.amazon.com/sp-api/docs/listings-management-workflow-migration)
- Our listings [playlist](https://www.youtube.com/watch?v=-box2_OmQpE&list=PLUFIeZA9F5PxOt0_Mql1KFmusySdpGmYV) on Youtube

Best,
Jawher
Selling Parnter API

**Comment by johnkw** [comment]
I see https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#creating-and-updating-listings-items-in-bulk yes.

But where is the new step 1?  It skips over step 1 entirely now and starts talking about other details.

The old step 1 is "Go to https://sellercentral.amazon.com/listing/cards/add-product?style=standalone and type in your product type." and from there everything else is super easy.

What is the new URL to go to on SellerCentral in order to download a `JSON_LISTINGS_FEED` compatible file?

**Comment by jawheral** [comment]
Hi @johnkw,

You don't need to go to Seller Central. The JSON_LISTINGS_FEED as the name implies is json based. Basically, the feed payload is in JSON format and the structure/data validation is governed by a json schema.

The schema for the JSON_LISTINGS_FEED can be found [here](https://github.com/amzn/selling-partner-api-models/tree/main/schemas/feeds) with examples of how it looks like.

The schemas for listings attributes (each message in the feed), depend on the product type and can be fetched from the Product Type Definitions API using the getDefinitionsProductType operation.

[You can find some JSON_LISTINGS_FEED body example [here](https://developer-docs.amazon.com/sp-api/docs/listing-workflow-migration-tutorial](https://github.com/amzn/selling-partner-api-models/blob/main/schemas/feeds/listings-feed-schema-v2.example.json). By inspecting the body, you find a _productType_ attribute ("productType": "LUGGAGE" in the example).
As mentioned in the guide, JSON_LISTINGS_FEED and the Listings Items API are contractually compatible. Given you use the same productType and operation the attributes will be governed by the same schema.

I hope this helps!

Best,
Jawher
Selling Partner API

**Comment by johnkw** [comment]
Well thank you, however that doesn't solve the problem.

We need a new step 1/2 for the new workflow.  So we need to be able to download a file somewhere that has the list of the relevant columns for a given product category, along with documentation for each of the columns, and what the valid values are, and the meaning of those values. Currently, all of that is in the XLSX file from steps 1/2 in the current workflow.

So we need an equivalent file to download for `JSON_LISTINGS_FEED`, or some way to have `JSON_LISTINGS_FEED` accept the same column names that the currently-available XLSX file uses, or some documentation embedded in the XLSX to translate each of the normal column names into a `JSON_LISTINGS_FEED` hierarchical path.

**Comment by leonardonakagawa** [comment]
Hi @johnkw,

For the API layer, what you mention can be done by using the [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference). 

It gives you all the Attributes and valid values needed in a localized form (en_US or pt_BR) for example.

The columns from the Flat-File in the Seller Central are the attributes which you will retrieve using the [getDefinitionsProductType](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#getdefinitionsproducttype) operation. You will be able to parse the JSON schema and read relevant attributes and valid values.

I recommend you check the [Product Type Definitions API v2020-09-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide) for further information.

Keep us posted if this is what you are looking for.

All the best,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by johnkw** [comment]
That example JSON doesn't make much sense to me. The current CSV for one of our products has 485 columns. The column names are things like "protein_per_serving_unit_of_measure". What we would need is a document with at least 485 entries, that lists every possible column for the current system, and the corresponding JSON hierarchy thing. Where is there something like that?

**Comment by jawheral** [comment]
Hi @johnkw,

There is no file or template that we can provide as the new Listings Workflow is based on dynamic Product Type Definitions, which you can access through the [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference).

In order to map the current XML and Flat File feeds to the JSON-based feeds and the Listings Items API, please refer to this [page](https://developer-docs.amazon.com/sp-api/docs/mapping-product-attributes) which is part of the Listings Management Workflow [Migration](https://developer-docs.amazon.com/sp-api/docs/listings-management-workflow-migration).

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by johnkw** [comment]
Thanks so on that page there is a link to [Product Flat File Mappings](https://m.media-amazon.com/images/G/01/VSSC/FlatFile-To-JSON-Mapping.xlsx) which is the sort of thing that would be used after the original step 1 in order to translate the documented feed file over to the JSON paths for API use.

However I just checked and the following columns are all missing from that xlsx file:

`'package_contains_identifier', 'other_image_url8', 'quantity_price_type', 'swatch_image_url', 'restock_date', 'sale_from_date', 'map_price', 'offer_image4', 'feed_product_type', 'quantity', 'standard_price', 'progressive_discount_type', 'net_content_volume1', 'progressive_discount_lower_bound1', 'net_content_volume_unit_of_measure1', 'net_content_volume2', 'back_bottle_image_url', 'offering_end_date', 'shaft_style_type', 'net_content_volume_unit_of_measure2', 'back_label_image_url', 'offer_image3', 'fulfillment_center_id', 'sale_end_date', 'business_price', 'quantity_lower_bound5', 'progressive_discount_value1', 'item_dimensions_unit_of_measure', 'relationship_type', 'quantity_price5', 'update_delete', 'other_image_url7', 'sale_price', 'front_bottle_image_url', 'progressive_discount_lower_bound3', 'fulfillment_latency', 'offering_start_date', 'quantity_lower_bound2', 'other_image_url1', 'other_image_url6', 'other_image_url2', 'other_image_url4', 'offer_image5', 'quantity_price4', 'main_image_url', 'quantity_lower_bound1', 'offer_image2', 'progressive_discount_lower_bound2', 'quantity_price3', 'quantity_lower_bound3', 'package_contains_quantity', 'other_image_url3', 'quantity_lower_bound4', 'progressive_discount_value2', 'offer_image1', 'progressive_discount_value3', 'quantity_price2', 'pricing_action', 'other_image_url5', 'quantity_price1', 'parent_sku', 'package_dimensions_unit_of_measure'`

Please update the xlsx to include the missing columns?

**Comment by jawheral** [comment]
@johnkw As in the documentation, the file only shows product-related attributes. Attributes that are offer-related and other not-relevant anymore or marketplace/productType specific attributes won't be available in that file. (The attributes you shared fall under this)
The migration is to be done in conjunction with Product Type Schemas.  

> The mappings in these files are limited to product-related attributes (that is, they do not include inventory or pricing) and do not include the product type or marketplace-specific relevancy of each. The [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference) provides JSON Schemas that represent the applicable attributes and constraints per product type and marketplace. Using the mapping files in conjunction with the JSON Schemas will let you to update your data mappings, identify which mappings are relevant for each product type and marketplace, identify data elements no longer relevant, and identify new relevant data elements.

**Comment by johnkw** [comment]
So what's the answer? Is it clear at this point what a gigantic time-suck this is for the users? We need more documentation on mapping the values over. So just to take one example from the list above, what is the map for `other_image_url6`?

**Comment by weilinggu** [comment]
@johnkw Similar to the step 1 you mentioned here (Go to https://sellercentral.amazon.com/listing/cards/add-product?style=standalone and type in your product type.)

In the Listings API workflow, if you know what product type you want to use, you can call [GET /definitions/2020-09-01/productTypes/{productType}](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#get-definitions2020-09-01producttypesproducttype), which will return a product type JSON schema that shows the data requirement for submitting a listing of that product type. [Here](https://www.youtube.com/watch?v=fraQT3UhFII) is a video series that explains how to use the product type JSON schema.

You can use the product type JSON schema to render a form or validate your product payload before submitting. [Here](https://json-schema.org/tools?query=&sortBy=name&sortOrder=ascending&groupBy=toolingTypes&licenses=&languages=&drafts=&toolingTypes=) are some publicly available tools for JSON schema.

Thanks
Weiling
Selling Partner Developer Services

**Comment by johnkw** [comment]
That is not a good substitute for the current workflow in comment 0.  The https://sellercentral.amazon.com/listing/cards/add-product?style=standalone page has a web-search style user-friendly search with documentation in the page explaining what your options are.

We need a way to convert from the spreadsheet templates that https://sellercentral.amazon.com/listing/cards/add-product?style=standalone returns to the new pointlessly-reformatted JSON templates.  Surely there's a way to map from one to the other?

**Comment by johnkw** [comment]
Any update on this? Why is (for example) `other_image_url6` not present in the [Product Flat File Mappings](https://m.media-amazon.com/images/G/01/VSSC/FlatFile-To-JSON-Mapping.xlsx)?

It's worth noting in https://github.com/amzn/selling-partner-api-models/issues/572 someone posted that a 3rd-party SaaS company created a proprietary conversion utility, due to the fact that this API currently provides no documented migration path.  If the FlatFile-To-JSON-Mapping.xlsx were updated (and always kept updated) for the https://sellercentral.amazon.com/listing/cards/add-product?style=standalone page, then the migration path would be clear (although cumbersome).

**Comment by rodrifed** [comment]
Hi @johnkw,

Please note that the legacy XML and Flat File schemas don't always support all attributes for a specific category.
The JSON schemas from the Product Type Definition API, however, always include the most up-to-date attribute definition.

The reasons why an attribute is missing from the mapping file could be:
1. The attribute is somewhat new and wasn't supported in the legacy XML and Flat File schemas
2. The attribute was renamed/removed, and is therefore not part of the new JSON schema

In both scenarios above, there is no valid mapping, therefore the attribute is not included in the mapping file.

I hope the information above is useful.

Thanks,
Federico
Selling Partner Developer Services

**Comment by johnkw** [comment]
The `other_image_url6` field is not new. It's been part of ASIN definitions for many many years.
It's not been renamed or removed.

Either way though, if it's missing from the JSON, then the JSON is broken and needs to be fixed.

The deprecation date for the current working API should be extended, until all fields have a valid mapping in the JSON.

**Comment by rodrifed** [comment]
Hi @johnkw,

The JSON schemas always include the most up-to-date attributes.
If you call the [/getDefinitionsProductType](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#getdefinitionsproducttype) operation with `productType = PRODUCT`, which returns the base attribute information shared across all categories, you will find the `other_product_image_locator_6` attribute. I understand this is the attribute you are looking for.

Best,
Federico
Selling Partner Developer Services

**Comment by johnkw** [comment]
Ok, but where is the file to download or call to make that ties the two together? Something needs to indicate that `other_image_url6` got renamed to `other_product_image_locator_6`.

**Comment by rodrifed** [comment]
Hi @johnkw,

For various reasons, some attributes are not included in the mapping files.
You can find image-related attribute information in the following link: https://developer-docs.amazon.com/sp-api/docs/mapping-product-attributes#image-type-mappings.

Best,
Federico
Selling Partner Developer Services

**Comment by johnkw** [comment]
Can we please leave this ticket open until it's fixed? This is still highly broken. 

Where can we get a file in a programmatic format (like CSV) that corresponds to https://developer-docs.amazon.com/sp-api/docs/mapping-product-attributes#image-type-mappings  ?

**Comment by johnkw** [comment]
They perhaps are vaguely outlined in that https://developer-docs.amazon.com/sp-api/docs/mapping-product-attributes#inventory-feed-mappings documentation, but what's needed is a programmatically-accessible list.
